import { DeckId } from './deckStorage';

// Import all generated prose files using Vite's glob import
// These files are generated by scripts/generateProse.js
const proseFiles = import.meta.glob('../config/topicProse/*.txt', { eager: true, as: 'raw' });

/**
 * Get the prose file key for a topic
 */
function getProseFileKey(topicId: string, deckId: DeckId): string | null {
  // Normalize topic ID (handle variations)
  let normalizedTopicId = topicId;
  if (topicId === 'agent' || topicId === 'agents') {
    normalizedTopicId = 'agents';
  } else if (topicId === 'pattern' || topicId === 'patterns') {
    normalizedTopicId = 'patterns';
  } else if (topicId === 'task' || topicId === 'task-creator') {
    normalizedTopicId = 'task-creator';
  } else if (topicId === 'choice' || topicId === 'choice-hierarchy') {
    normalizedTopicId = 'choice-hierarchy';
  }

  const expectedKey = `../config/topicProse/${deckId}-${normalizedTopicId}.txt`;
  
  // Check if the file exists in the glob
  if (expectedKey in proseFiles) {
    return expectedKey;
  }

  return null;
}

/**
 * Generate prose explanation for a topic
 * Loads pre-generated prose from config/topicProse/ files
 */
export function generateTopicProse(topicId: string, deckId: DeckId): string {
  const fileKey = getProseFileKey(topicId, deckId);
  
  if (!fileKey) {
    return `No prose file found for topic "${topicId}" in deck "${deckId}".`;
  }

  const prose = proseFiles[fileKey] as string | undefined;
  
  if (!prose) {
    return `Unable to read prose file for topic "${topicId}".`;
  }

  return prose.trim();
}

